/* MIGRATION TEMPLATE */
/* DO NOT DELETE TEMPLATE COMMENTS! */

/* --- */

/*START MIGRATION UP*/

CREATE TABLE weight (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(100) NOT NULL,
    kilograms DOUBLE NOT NULL,
    seconds INT UNSIGNED NOT NULL
);

/*END MIGRATION UP*/

/* --- */

/*START MIGRATION DOWN*/

DROP TABLE weight;

/*END MIGRATION DOWN*/
