/* MIGRATION TEMPLATE */
/* DO NOT DELETE TEMPLATE COMMENTS! */

/* --- */

/*START MIGRATION UP*/

ALTER TABLE measurement MODIFY COLUMN metric_id INT UNSIGNED NOT NULL;

/*END MIGRATION UP*/

/* --- */

/*START MIGRATION DOWN*/

ALTER TABLE measurement MODIFY COLUMN metric_id INT NOT NULL;

/*END MIGRATION DOWN*/
